apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-1c512ee817f142b8bd7eeca95913f50c-depl
  labels:
    app: coll-1c512ee817f142b8bd7eeca95913f50c
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-1c512ee817f142b8bd7eeca95913f50c
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-1c512ee817f142b8bd7eeca95913f50c
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-1c512ee817f142b8bd7eeca95913f50c
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-1c512ee817f142b8bd7eeca95913f50c
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping