apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::216084506783:user/kathy-ci-cd
      username: kathy-ci-cd 
      groups:
        - system:masters