apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-cc7e2b3fc93243f3bff050d88a3bd6fa-depl
  labels:
    app: coll-cc7e2b3fc93243f3bff050d88a3bd6fa
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-cc7e2b3fc93243f3bff050d88a3bd6fa
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-cc7e2b3fc93243f3bff050d88a3bd6fa
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-cc7e2b3fc93243f3bff050d88a3bd6fa
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-cc7e2b3fc93243f3bff050d88a3bd6fa
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping