apiVersion: v1
kind: Service
metadata:
  name: coll-cc7e2b3fc93243f3bff050d88a3bd6fa-srv
spec:
  selector:
    app: coll-cc7e2b3fc93243f3bff050d88a3bd6fa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP