apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-c84f7baf24c64be8add668ef9c4ceb6a-depl
  labels:
    app: coll-c84f7baf24c64be8add668ef9c4ceb6a
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-c84f7baf24c64be8add668ef9c4ceb6a
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-c84f7baf24c64be8add668ef9c4ceb6a
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-c84f7baf24c64be8add668ef9c4ceb6a
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-c84f7baf24c64be8add668ef9c4ceb6a
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping